//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaPortolfyoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int AboutID { get; set; }
        public string ImageURL { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Website { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public Nullable<byte> Age { get; set; }
        public string Email { get; set; }
        public string FreeLance { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Degree { get; set; }
    }
}
