//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaPortolfyoProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbAcunMedyaProject1Entities2 : DbContext
    {
        public DbAcunMedyaProject1Entities2()
            : base("name=DbAcunMedyaProject1Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<About> About { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Communication> Communication { get; set; }
        public DbSet<Contact> Contact { get; set; }
        public DbSet<Education> Education { get; set; }
        public DbSet<Job> Job { get; set; }
        public DbSet<Project> Project { get; set; }
        public DbSet<Services> Services { get; set; }
        public DbSet<Skill> Skill { get; set; }
        public DbSet<Slider> Slider { get; set; }
        public DbSet<Testimonial> Testimonial { get; set; }
    }
}
