//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaPortolfyoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int SkillID { get; set; }
        public string SkillName { get; set; }
        public Nullable<byte> Derece { get; set; }
        public string Description { get; set; }
    }
}
